# This is a general macro for testing features of the
# RICOCHET/REvOLT-0 Monte Carlo v0.1 (RMC)
#
# Adam Anderson
# adama@mit.edu
#

/control/verbose 1
/run/verbose 1
/RMC/verbose 1

/RMC/Lab MITReactor
/RMC/UseShield true
/RMC/UseCryostat true
/RMC/UseTower true
/RMC/Source neutronwall
/RMC/updateGeom

/vis/open OGLIX 600x600-0+0
/vis/verbose errors
/vis/viewer/set/upVector 0 0 1
/vis/viewer/set/viewpointThetaPhi 60 250 #85 270		# Slightly tilted
/vis/viewer/addCutawayPlane 0 0 0 m 0 1 0
/vis/drawVolume
/vis/scene/endOfEventAction accumulate
#/vis/scene/add/axes 3.5 0 1.5 2 m
#/vis/viewer/flush
/vis/viewer/zoomTo 10
/vis/viewer/pan 2 2 m

/run/beamOn 3000